### ISSUE TITLE
Get the current page number

### ISSUE THREAD

**Issue by milligator** [AndrewSB/PageViewDemo#1]
Hi.
I tried to get the page number through the index parameter of this function. I added a line of code to get that number. But it is sometimes one step ahead and also sometimes it does not vary with reverse swipes.How can I access the current page number?

```
 func viewControllerAtIndex(index: Int) -> TutorialViewController {
        let vc = UIStoryboard(name: "Main", bundle: nil).instantiateViewControllerWithIdentifier("tutorialVC") as! TutorialViewController
        vc.title = pageText[index]
        vc.pageIndex = index
        self.pageIndex = index
        print("\(index)") //****************
        return vc
    }
```

**Comment by AndrewSB** [comment]
Hey @milligator! I'm taking a look right now.
Out of curiosity, how did you find this project?

**Comment by AndrewSB** [comment]
@milligator I'm going to say that this repo of me trying out a pageViewController 2 years ago was terrible, and I'd recommend not using it as a reference example.

For the problem you're facing with unreliable page indices, I contributed to [Ello](http://ello.co/)'s iOS app not too long ago, and have a pretty good implementation in my pull request there (https://github.com/ello/ello-ios/pull/56/files) take a look and see if that works for you.

Let me know if theres anything else you need from this 👍

**Comment by milligator** [comment]
@AndrewSB I was just looking for an implementation of UIPageViewController with a still background. I found it what I really needed. My still background is a UILabel but yours is an UIImageView.

**Comment by milligator** [comment]
I need to present dynamic contents, like different pdf files or photos of my albums.

**Comment by AndrewSB** [comment]
Interesting -- well I'm happy I could be an example of having a static background for a UIPageViewController!

The interesting parts of my implementation were:
1. Make the UIPageViewController's `backgroundColor = .clear`
2. Make each of the content view controllers (i.e. the view controllers that are placed into `pageVC.viewControllers`) `backgroundColor = .clear`
3. Add a subview of a (`UILabel`|`UIImageView`|`PDF`) to the UIPageViewController
4. 💸

**Comment by milligator** [comment]
The 3rd one was amazing for me.
Despite all my efforts, I could not get the current page number correctly.
So I decided to find another solution. Now I am trying to use UIcollectionView.

**Comment by AndrewSB** [comment]
are you sure? I can try to help you out. Do you want to call me? I can look at your problem.

I'm asbreckenridge on google hangouts

**Comment by milligator** [comment]
Dear andrew, it would be my pleasure to have direct contact with you
Thank you

**Comment by AndrewSB** [comment]
go ahead and message me! I'll talk to you soon 😄
